---
- name: Deploy Ceph-OpenStack servers
  hosts: all
  become: yes
  become_user: root

  roles:
      - createusers
      - sudoers
      - nameserver_local
      - repo_local_7.8.2003
      - chrony
      - bashrc
      - motd
      - logrotate
      - rsyslog
      - route-vlan112
      - SELinux_Firewall_local
      - reboot
      - update
      - install_packages
      - zabbix
      - lldpd
      - ssh
      - change_root_pwd
